### ISSUE TITLE
長時間播放不中斷，循環，清單功能的各種組合是否能正確運行 

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-android#11]

**Comment by 1314main** [comment]
循環＆清單 運行ok

**Comment by shuping2021** [comment]
之前原有的音檔測試：
1.循環 on & 清單 on => OK
2.循環 off & 清單 on => OK
3.循環 on & 清單 off => OK
4.循環 off & 清單 off => OK
5.長時間播放 => 測試到目前為止都OK

居家結構調整：
1.循環 on & 清單 on => OK
2.循環 off & 清單 on => OK
3.循環 on & 清單 off => OK
4.循環 off & 清單 off => OK

**Comment by shuping2021** [comment]
居家結構調整：
bug：
問題敘述：
1. 先播放一個音檔，從播放音檔跳出到主頁面
2. 點選居家結構調整
3. 直接選按影片上的播放鍵，此時會繼續播放上一個音檔，而不是播放影片。

**Comment by totality-of-life** [comment]
> 居家結構調整：
> bug：
> 問題敘述：
> 
> 1. 先播放一個音檔，從播放音檔跳出到主頁面
> 2. 點選居家結構調整
> 3. 直接選按影片上的播放鍵，此時會繼續播放上一個音檔，而不是播放影片。

感謝，這確實是個bug，下一個測試版會修好

**Comment by cdsmilk** [comment]
Bug同shuping2021
1. 先播放一個音檔 ex讀書會，從播放音檔跳出到主頁面
2. 再點選另一主題的音檔ex沒有路的路，按下播放鍵，會繼續播上一個音檔。
3. 之前app版本播音檔時，跳到主頁面或關掉app，音檔會中斷，回頭聽會從中斷的地方繼續播。
現在版本 : 比如聽讀書會音檔01-->跳到主畫面或關掉app-->再次開啟進入讀書會，音檔01接續播沒問題，但如果點選其他主題ex沒有路的路，再點回讀書會，就無法從中斷的地方繼續聽。

**Comment by totality-of-life** [comment]
感謝兩位回報，這個應該已經修好了，明天就會可以下載修改好的測試版

**Comment by shuping2021** [comment]
> > 居家結構調整：
> > bug：
> > 問題敘述：
> > 
> > 1. 先播放一個音檔，從播放音檔跳出到主頁面
> > 2. 點選居家結構調整
> > 3. 直接選按影片上的播放鍵，此時會繼續播放上一個音檔，而不是播放影片。
> 
> 感謝，這確實是個bug，下一個測試版會修好

今天中午下載更新版，重新測試，此問題已經修好了，謝謝Andy！

**Comment by bueggtw04** [comment]
循環與清單功能 測試正常

**Comment by Happyscorpion** [comment]
我們家有1支安卓HTC手機，1支iphone，都有載全部生命APP，我最近發現我最常用來聽博士音檔的的HTC手機常常會自主循環播放，取消循環功能之後，隔一陣子後，還是出現循環播放，我查看其他手機發現iphone上的APP有選取循環播放功能，是不是手機上的APP的循環播放跟愛心功能一樣是雲端同步?

但這情形好像也不固定，我現在還很疑惑，但我想我就先回報~

**Comment by totality-of-life** [comment]
> 我們家有1支安卓HTC手機，1支iphone，都有載全部生命APP，我最近發現我最常用來聽博士音檔的的HTC手機常常會自主循環播放，取消循環功能之後，隔一陣子後，還是出現循環播放，我查看其他手機發現iphone上的APP有選取循環播放功能，是不是手機上的APP的循環播放跟愛心功能一樣是雲端同步?
> 
> 但這情形好像也不固定，我現在還很疑惑，但我想我就先回報~

感謝回報，循環跟清單沒有寫同步功能。
對了，每個專輯中的循環跟清單是屬於那個專輯本身的喔，不是整個app共同的設定
其他就等我實驗看看會不會發生這個情況，謝謝

**Comment by Happyscorpion** [comment]
> > 我們家有1支安卓HTC手機，1支iphone，都有載全部生命APP，我最近發現我最常用來聽博士音檔的的HTC手機常常會自主循環播放，取消循環功能之後，隔一陣子後，還是出現循環播放，我查看其他手機發現iphone上的APP有選取循環播放功能，是不是手機上的APP的循環播放跟愛心功能一樣是雲端同步?
> > 但這情形好像也不固定，我現在還很疑惑，但我想我就先回報~
> 
> 感謝回報，循環跟清單沒有寫同步功能。 對了，每個專輯中的循環跟清單是屬於那個專輯本身的喔，不是整個app共同的設定 其他就等我實驗看看會不會發生這個情況，謝謝

實驗的時候可以拉長一點時間試看看~可能等個1-2天。
我有重複實驗過，我那支HTC手機有隔一天才會突然自主循環播放的情形，不太一定。
謝謝你，辛苦了

**Comment by totality-of-life** [comment]
有沒有可能是螢幕髒了，然後某個污點造成觸控螢幕誤判按了循環那個按鈕？

**Comment by Happyscorpion** [comment]
> 有沒有可能是螢幕髒了，然後某個污點造成觸控螢幕誤判按了循環那個按鈕？

不知道耶，我重新擦過了手機，我會再觀察看看~

**Comment by nimaharmer** [comment]
Ok
