### ISSUE TITLE
電話或簡訊中斷後，音檔自動接續播放

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-android#12]

**Comment by shuping2021** [comment]
之前原有的音檔：
1.電話進來後，中斷播放，電話結束時，繼續播放 => OK
2.簡訊進來時，中斷播放，隨之接著繼續播放 => OK

居家結構調整：
1.電話進來後，中斷播放，電話結束時，繼續播放 => OK
2.簡訊進來時，只是聲音頓了一下，隨之接著繼續播放 => OK

**Comment by cdsmilk** [comment]
打電話給別人，會中斷播放。結束通話，繼續播放=>ok

**Comment by roger-chuang** [comment]
音檔撥放中，我測試line通話狀況，
之前的版本有別人打line進來通話，講完line後音檔是暫停狀態，要手動按撥放才會繼續，
2.0測試版別人打line進來通話，還有用line打給別人，掛完電話後音檔會自動繼續撥放(通話時是暫停狀態)，
前後版本有所不同。

**Comment by Happyscorpion** [comment]
電話或簡訊中斷後，音檔自動接續播放 (yes)

我是用Google Meet 視訊測試

**Comment by kuogene** [comment]
SONY XZ1/Android 9
電話進來後，中斷播放，電話結束時，繼續播放 => OK

**Comment by Hsuan-fei** [comment]
三星，Abdroid 10
電話、簡訊、Line進來後，中斷播放，結束時，繼續播放 => OK

**Comment by nimaharmer** [comment]
不會繼續播放

**Comment by totality-of-life** [comment]
> 不會繼續播放

我剛剛試沒問題，可以描述一下做了什麼操作嗎？

**Comment by nimaharmer** [comment]
不好意思，我是描述平常使用正式App時如果接電話會中斷，但掛斷並不會自動接續播放的情況
安裝好測試版後並沒正好有電話進來

totality ***@***.***> 於 2022年9月9日 週五 10:51 寫道：
