### ISSUE TITLE
同帳號的愛心可否正常再多個設備間同步，例如Android 手機跟平板，甚至iPhone，iPad(打開App的瞬間才會從雲端下載）

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-android#13]
這個功能如果同時打開兩個設備A跟B，如果Ａ，Ｂ的愛心有更動，會以最後一個更動的設備的“全部愛心的情況”為主，沒有聰明到記錄單個音檔的最新的愛心情況。

簡單講就是哪個設備的資料最新，就以那個設備為準。

備份愛心是這個功能最主要的目的，簡單的同步算是一個附加功能。

應該不多人要同時在兩個設備上面加愛心吧？
如果我想錯了可以跟我說

**Comment by shuping2021** [comment]
我找了一台舊手機( android版本：7.0 NRD90M)做測試。
兩個手機之間愛心的同步有個問題，以下是reproduce steps:
1.A手機在"沒有路的路"設定幾個愛心後，離開APP，回到手機頁面
2.B手機打開APP，進入"沒有路的路"，此時看到的愛心設定是原本在B手機設定的愛心
3.B手機離開APP，回到手機頁面
4.A手機再次打開APP後，B手機的愛心設定才會顯示A手機的愛心設定
換言之，愛心設定須在重新啟動APP時，另一個mobile device才會同步更新。

**Comment by totality-of-life** [comment]
首先要2.0版才有這功能喔
如果有網路，按愛心的瞬間，會回傳一次”全部愛心的情形+最後修改愛心的時間“到雲端的server存下來
如果沒有網路，那這次會失敗，下次打開app的瞬間，如果有網路會上傳，也會下載server的那一版
不管A,B,Server這三個版本間，都是“最後修改愛心時間”最新的那一個版本，在同步的時候會當作最終的版本

你的情形我猜幾個可能會發生
1. A, B手機設定的時間可能不準，因為是依造手機本身的時間來判斷
2.  打開Ｂ手機的時候有按到愛心，有變動，所以變成B手機的愛心情況被當作最終的版本
3. 可能我哪邊有寫錯，這要找找，哈哈

**Comment by shuping2021** [comment]
A、B手機都是2.0測試版，時間都是一樣的，有交叉測試過。
做測試時，只在A手機上選按愛心設定，然後B手機對愛心完全沒動作，只是想方設法看到A手機的設定出現 (^_^)  
也有可能是我的手機個別問題，希望夥伴們能找多一點的mobile device測試看看~

**Comment by totality-of-life** [comment]
我剛修改好另一個bug，上傳了一個新的測試版本上去，正在審核，好了google會自動發佈
我沒有兩隻android手機可以實驗，我拿ios 跟 android 一起實驗看看，我上次測這件事已經很久以前了，說不定不小心弄壞了

**Comment by shuping2021** [comment]
Andy, 您辛苦了！  
等拿到新版本，我再來試看看~

**Comment by totality-of-life** [comment]
感謝你，我發現Android版本按下愛心的時候沒有上傳，漏掉了，以為自己寫過了ＸＤ
趕快把剛剛那個測試版退回來，連同這個修好再上傳，感恩

**Comment by shuping2021** [comment]
> 感謝你，我發現Android版本按下愛心的時候沒有上傳，漏掉了，以為自己寫過了ＸＤ
> 趕快把剛剛那個測試版退回來，連同這個修好再上傳，感恩

今天中午下載更新版，重新測試。這個問題依然存在，尚未解決~
麻煩您了，謝謝！

**Comment by Miffy9145** [comment]
同帳號的愛心可否正常再多個設備間同步，例如Android 手機→可以
要二支手機同步驗證碼，以及例如：A按愛心，B要先退出app在登入才能抓取(反之，也是)
比較保險的做法是調整二支手機的愛心後，二支手機都先退出app，就能"(打開App的瞬間才會從雲端下載)"

**Comment by shuping2021** [comment]
1. 最新的版本應該把大家在Github的問題都修正了，如果有漏掉的，請提醒我。=> 有bug
        bug: 在兩個android手機測試愛心設定時，發現不管A或B device做任何的愛心設定變更，都會回到原來一開始的愛心設定。

2. 多國語言包括連UI的部分都翻譯完成  => 測試OK
3. 播放音檔的列表，進入的時候，在本機，會自動滑動至上次最後播放的檔案位置，在雲端，會自動滑到最下面。 => 測試OK
4. 主頁帳號跟最新消息都改成圖示，帳號移動到左邊去，最新消息在右邊。盡可能避免字體條大的時候把帳號功能擠出螢幕，造成使用者找不到帳號頁。 => 測試OK

**Comment by totality-of-life** [comment]
> 1. 最新的版本應該把大家在Github的問題都修正了，如果有漏掉的，請提醒我。=> 有bug
>    bug: 在兩個android手機測試愛心設定時，發現不管A或B device做任何的愛心設定變更，都會回到原來一開始的愛心設定。

我自己在android跟iphone兩台手機之間測試是正常的，android手機跟android模擬器之間測試也是正常的，我沒有兩台android手機可以實驗。

從描述的情況，我目前只能猜測曾經手機有時間設定到一個未來的時間點，所以那次上傳到後台的愛心一直被當作最新版本。

我從後台有看到一個帳號愛心的時間是Friday, October 1, 2021 7:08:54 PM GMT+08:00，是未來的時間，其他帳號都差不多日期，我先修正成目前的日期，這樣應該功能就可以正常的使用了。

我之後也會寫一個簡單的檢查，讓就算手機不小心日期跑掉也不會發生這個bug，感謝妳的回報

可以請妳email回信告訴我妳手機號碼，讓我可以確認一下是不是這個原因造成的，不是的話就還要再找找，謝謝

ps.因為我今天白天都不會在電腦前面，所以可能要晚上才能繼續處理

**Comment by shuping2021** [comment]
> > 1. 最新的版本應該把大家在Github的問題都修正了，如果有漏掉的，請提醒我。=> 有bug
> >    bug: 在兩個android手機測試愛心設定時，發現不管A或B device做任何的愛心設定變更，都會回到原來一開始的愛心設定。
> 
> 我自己在android跟iphone兩台手機之間測試是正常的，android手機跟android模擬器之間測試也是正常的，我沒有兩台android手機可以實驗。
> 
> 從描述的情況，我目前只能猜測曾經手機有時間設定到一個未來的時間點，所以那次上傳到後台的愛心一直被當作最新版本。
> 
> 我從後台有看到一個帳號愛心的時間是Friday, October 1, 2021 7:08:54 PM GMT+08:00，是未來的時間，其他帳號都差不多日期，我先修正成目前的日期，這樣應該功能就可以正常的使用了。
> 
> 我之後也會寫一個簡單的檢查，讓就算手機不小心日期跑掉也不會發生這個bug，感謝妳的回報
> 
> 可以請妳email回信告訴我妳手機號碼，讓我可以確認一下是不是這個原因造成的，不是的話就還要再找找，謝謝
> 
> ps.因為我今天白天都不會在電腦前面，所以可能要晚上才能繼續處理

早上確認過，的確有支手機的時間被手動調整過了，應該就是您說的這個問題，您辛苦了，謝謝您！
另外，依照您的說法，愛心標記是以時間為主軸來判定先後順序，所以即使手機時間改回網路設定時間(正確的時間)，愛心設定仍會以之前在未來時間(最晚的時間)的設定為其設定。
是否能考慮"愛心設定"與"時間設定"脫離，不要綁在一起呢？ 這樣就不會受時間設定影響了！

**Comment by totality-of-life** [comment]
> > > 1. 最新的版本應該把大家在Github的問題都修正了，如果有漏掉的，請提醒我。=> 有bug
> > >    bug: 在兩個android手機測試愛心設定時，發現不管A或B device做任何的愛心設定變更，都會回到原來一開始的愛心設定。
> > 
> > 
> > 我自己在android跟iphone兩台手機之間測試是正常的，android手機跟android模擬器之間測試也是正常的，我沒有兩台android手機可以實驗。
> > 從描述的情況，我目前只能猜測曾經手機有時間設定到一個未來的時間點，所以那次上傳到後台的愛心一直被當作最新版本。
> > 我從後台有看到一個帳號愛心的時間是Friday, October 1, 2021 7:08:54 PM GMT+08:00，是未來的時間，其他帳號都差不多日期，我先修正成目前的日期，這樣應該功能就可以正常的使用了。
> > 我之後也會寫一個簡單的檢查，讓就算手機不小心日期跑掉也不會發生這個bug，感謝妳的回報
> > 可以請妳email回信告訴我妳手機號碼，讓我可以確認一下是不是這個原因造成的，不是的話就還要再找找，謝謝
> > ps.因為我今天白天都不會在電腦前面，所以可能要晚上才能繼續處理
> 
> 早上確認過，的確有支手機的時間被手動調整過了，應該就是您說的這個問題，您辛苦了，謝謝您！ 另外，依照您的說法，愛心標記是以時間為主軸來判定先後順序，所以即使手機時間改回網路設定時間(正確的時間)，愛心設定仍會以之前在未來時間(最晚的時間)的設定為其設定。 是否能考慮"愛心設定"與"時間設定"脫離，不要綁在一起呢？ 這樣就不會受時間設定影響了！

我目前的想到的方法是，愛心回傳到server告訴的最新修改時間不可以超過當前server上的時間，如此一來，這個錯誤只會發生在那台時間有問題的設備，不會擴散，也不會害其他設備無法更新到server去。這要感謝妳讓我想到要做這件事，不然之後應該會有很多客服。

因為很多時候設備是離線使用，可能很久才會連回一次server，我還是必須有一個愛心修改的時間點當依據，才知道哪個愛心的紀錄是最新的版本。回傳server的時間點跟修改的時間點可能差非常多。

**Comment by shuping2021** [comment]
> > > > 1. 最新的版本應該把大家在Github的問題都修正了，如果有漏掉的，請提醒我。=> 有bug
> > > >    bug: 在兩個android手機測試愛心設定時，發現不管A或B device做任何的愛心設定變更，都會回到原來一開始的愛心設定。
> > > 
> > > 
> > > 我自己在android跟iphone兩台手機之間測試是正常的，android手機跟android模擬器之間測試也是正常的，我沒有兩台android手機可以實驗。
> > > 從描述的情況，我目前只能猜測曾經手機有時間設定到一個未來的時間點，所以那次上傳到後台的愛心一直被當作最新版本。
> > > 我從後台有看到一個帳號愛心的時間是Friday, October 1, 2021 7:08:54 PM GMT+08:00，是未來的時間，其他帳號都差不多日期，我先修正成目前的日期，這樣應該功能就可以正常的使用了。
> > > 我之後也會寫一個簡單的檢查，讓就算手機不小心日期跑掉也不會發生這個bug，感謝妳的回報
> > > 可以請妳email回信告訴我妳手機號碼，讓我可以確認一下是不是這個原因造成的，不是的話就還要再找找，謝謝
> > > ps.因為我今天白天都不會在電腦前面，所以可能要晚上才能繼續處理
> > 
> > 
> > 早上確認過，的確有支手機的時間被手動調整過了，應該就是您說的這個問題，您辛苦了，謝謝您！ 另外，依照您的說法，愛心標記是以時間為主軸來判定先後順序，所以即使手機時間改回網路設定時間(正確的時間)，愛心設定仍會以之前在未來時間(最晚的時間)的設定為其設定。 是否能考慮"愛心設定"與"時間設定"脫離，不要綁在一起呢？ 這樣就不會受時間設定影響了！
> 
> 我目前的想到的方法是，愛心回傳到server告訴的最新修改時間不可以超過當前server上的時間，如此一來，這個錯誤只會發生在那台時間有問題的設備，不會擴散，也不會害其他設備無法更新到server去。這要感謝妳讓我想到要做這件事，不然之後應該會有很多客服。
> 
> 因為很多時候設備是離線使用，可能很久才會連回一次server，我還是必須有一個愛心修改的時間點當依據，才知道哪個愛心的紀錄是最新的版本。回傳server的時間點跟修改的時間點可能差非常多。

呵呵！ 這個問題的出現只是剛剛好而已 (^_^)
您的這個做法也OK，只會影響到設定未來時間的行動裝置。若該裝置的系統時間重新設定為網路時間(正確的時間)，自然也能恢復正常使用。辛苦您了！ 謝謝！

**Comment by shuping2021** [comment]
> > > > 1. 最新的版本應該把大家在Github的問題都修正了，如果有漏掉的，請提醒我。=> 有bug
> > > >    bug: 在兩個android手機測試愛心設定時，發現不管A或B device做任何的愛心設定變更，都會回到原來一開始的愛心設定。
> > > 
> > > 
> > > 我自己在android跟iphone兩台手機之間測試是正常的，android手機跟android模擬器之間測試也是正常的，我沒有兩台android手機可以實驗。
> > > 從描述的情況，我目前只能猜測曾經手機有時間設定到一個未來的時間點，所以那次上傳到後台的愛心一直被當作最新版本。
> > > 我從後台有看到一個帳號愛心的時間是Friday, October 1, 2021 7:08:54 PM GMT+08:00，是未來的時間，其他帳號都差不多日期，我先修正成目前的日期，這樣應該功能就可以正常的使用了。
> > > 我之後也會寫一個簡單的檢查，讓就算手機不小心日期跑掉也不會發生這個bug，感謝妳的回報
> > > 可以請妳email回信告訴我妳手機號碼，讓我可以確認一下是不是這個原因造成的，不是的話就還要再找找，謝謝
> > > ps.因為我今天白天都不會在電腦前面，所以可能要晚上才能繼續處理
> > 
> > 
> > 早上確認過，的確有支手機的時間被手動調整過了，應該就是您說的這個問題，您辛苦了，謝謝您！ 另外，依照您的說法，愛心標記是以時間為主軸來判定先後順序，所以即使手機時間改回網路設定時間(正確的時間)，愛心設定仍會以之前在未來時間(最晚的時間)的設定為其設定。 是否能考慮"愛心設定"與"時間設定"脫離，不要綁在一起呢？ 這樣就不會受時間設定影響了！
> 
> 我目前的想到的方法是，愛心回傳到server告訴的最新修改時間不可以超過當前server上的時間，如此一來，這個錯誤只會發生在那台時間有問題的設備，不會擴散，也不會害其他設備無法更新到server去。這要感謝妳讓我想到要做這件事，不然之後應該會有很多客服。
> 
> 因為很多時候設備是離線使用，可能很久才會連回一次server，我還是必須有一個愛心修改的時間點當依據，才知道哪個愛心的紀錄是最新的版本。回傳server的時間點跟修改的時間點可能差非常多。

剛剛更新了最新測試版測試未來時間的問題，依照您的作法，測試結果OK。
辛苦了！謝謝您！
