### ISSUE TITLE
影片在休眠或關閉螢幕後還繼續播出聲音

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-android#14]
有人反應一邊做運動後來就只會聽指令，就把螢幕關著當音檔在聽，目前應該可以支援這樣的應用，大家可以試試看

**Comment by cdsmilk** [comment]
休眠跟關掉螢幕，聲音還繼續播。ok

**Comment by shuping2021** [comment]
休眠或關閉螢幕後還繼續播出聲音 => OK

**Comment by roger-chuang** [comment]
可以休眠或關閉螢幕收聽，因為我都是用藍芽耳機收聽，所以螢幕都會關閉或自動休眠，以前的版本和目前的測試版本都可以關閉螢幕收聽，都是OK的。

**Comment by Happyscorpion** [comment]
影片在休眠或關閉螢幕後還繼續播出聲音  (yes)

**Comment by kuogene** [comment]
SONY XZ1/Android 9
休眠或關閉螢幕後還繼續播出聲音 => OK

**Comment by coolbil** [comment]
Android 10
Samsung S10
休眠或關閉螢幕後還繼續播出聲音 => OK

**Comment by cdsmilk** [comment]
我有個疑問，手機有設定休眠時間，時間到就會關掉螢幕，但如果我要一直看影片，就得把休眠關掉或延長或是一直點按變暗的螢幕。可以像看YouTube一樣，螢幕一直顯示，除非自己主動關掉嗎？還是目前沒有要這樣設計？先謝謝回答。🙂

**Comment by totality-of-life** [comment]
> 我有個疑問，手機有設定休眠時間，時間到就會關掉螢幕，但如果我要一直看影片，就得把休眠關掉或延長或是一直點按變暗的螢幕。可以像看YouTube一樣，螢幕一直顯示，除非自己主動關掉嗎？還是目前沒有要這樣設計？先謝謝回答。🙂

謝謝提醒，我找找，應該做得到

**Comment by Miffy9145** [comment]
休眠或關閉螢幕(休眠模式)後還繼續播出聲音 → OK

**Comment by bueggtw04** [comment]
關閉螢幕時, 可以持續播出音檔。

**Comment by 1220tammy** [comment]
關螢幕可持續播放音檔  👍

**Comment by Happyscorpion** [comment]
更新後測試
影片在休眠或關閉螢幕後還繼續播出聲音 => OK

**Comment by Hsuan-fei** [comment]
休眠或關閉螢幕後還繼續播出聲音 => OK

但請問，這個討論區與 [2.2版聽一段時間後自動停止] 是一樣的問題嗎？因為我有回覆到那邊，不知道這裡是否需要再貼一次。謝謝

**Comment by totality-of-life** [comment]
> 休眠或關閉螢幕後還繼續播出聲音 => OK
> 
> 但請問，這個討論區與 [2.2版聽一段時間後自動停止] 是一樣的問題嗎？因為我有回覆到那邊，不知道這裡是否需要再貼一次。謝謝

不是，這個是專門針對影片，當初測試的時候有個朋友提出來的需求，他覺得運動影片也要在螢幕關上的時候繼續播放，把影片的背景音樂當作放純音樂來運動。我們平常一般的播影片軟體，關上螢幕會自動暫停，本來看影片沒螢幕那要看什麼。

後來這就變成一個功能了，所以要測試一下是不是還正常運作。

**Comment by Hsuan-fei** [comment]
> > 休眠或關閉螢幕後還繼續播出聲音 => OK
> > 但請問，這個討論區與 [2.2版聽一段時間後自動停止] 是一樣的問題嗎？因為我有回覆到那邊，不知道這裡是否需要再貼一次。謝謝
> 
> 不是，這個是專門針對影片，當初測試的時候有個朋友提出來的需求，他覺得運動影片也要在螢幕關上的時候繼續播放，把影片的背景音樂當作放純音樂來運動。我們平常一般的播影片軟體，關上螢幕會自動暫停，本來看影片沒螢幕那要看什麼。
> 
> 後來這就變成一個功能了，所以要測試一下是不是還正常運作。

抱歉啊！沒看清楚是[影片]測試。
我剛剛也跑了一支影片，休眠或關閉螢幕後還繼續播出聲音 => OK

但好怪，播放聲音檔會有暫停的現象，就是 [2.2版聽一段時間後自動停止]描述的現象，但影片卻不會中斷。不知道是否因為聲音檔時間通常較長的緣故？或者這兩個問題根本不搭嘎？

沒關係，Andy不用特別回我。知道影片測試沒問題就好了~ ^^

**Comment by nimaharmer** [comment]
Ok

**Comment by NelsonAus** [comment]
Android 12 ,測試版和正常版，螢幕休眠或關閉約在6分鐘左右會自動跳出app並停止。

**Comment by totality-of-life** [comment]
> Android 12 ,測試版和正常版，螢幕休眠或關閉約在6分鐘左右會自動跳出app並停止。

我開了一個新issue專門追蹤這個問題，這次改版主要就是要解決這件事，你的手機現在是我的寶貴測試資源，因為目前只有你一個人回報發生，但新的手機應該越來越多會遇到
https://github.com/totality-of-life/testing-android/issues/30

Andy

**Comment by NelsonAus** [comment]
之後測試YouTube premium, 運行已下載影音，一樣在6分鐘左右閃退，但是運行live或需要網路支持的影音完全沒問題。

**Comment by totality-of-life** [comment]
> 之後測試YouTube premium, 運行已下載影音，一樣在6分鐘左右閃退，但是運行live或需要網路支持的影音完全沒問題。

你可以去購買手機的店面請服務人員幫忙找出為什麼youtube premium也會閃退嗎？因為如果是如此常見的軟體也會發生，他們應該很有經驗，到底是哪個設定造成的，然後知道了後，拜託告訴我

**Comment by totality-of-life** [comment]
https://github.com/totality-of-life/testing-android/issues/30

請到issue 30專門討論這個問題
