### ISSUE TITLE
多國語言支援，在帳號頁可以選擇語言（ 繁體中文、簡體中文、English）

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-android#17]
目前只有支援專輯名稱，歌曲及影片名稱
使用者介面跟錯誤訊息的文字因為比較多地方要改，如果這一版來不及，就等到下一版
讀書會當初只有中文的標題，如果未來博士給了英文標題會補上
兩次共修的每個音檔的英文標題是博士親自取的，推薦大家有興趣可以看看，說不會有什麼啟發

**Comment by bueggtw04** [comment]
在帳號頁好像沒有看到語言選擇的選項, 請問是尚未開放嗎? 多謝~

**Comment by totality-of-life** [comment]
抱歉，太早公佈。Android更新到play store要等一下子，可能幾個小時。謝謝

**Comment by john-huang-x** [comment]
只有選英文時，讀書會裡面標題還是中文
其他都OK

**Comment by Yunarena** [comment]
切換語言沒問題。
"Language"按鈕本身沒有切成繁中/簡中(這個應該算使用者介面)
沒有報名的課程可能是因為沒有影片的關係，所以專輯名稱有改語言，但內容影片標題維持繁體中文

**Comment by bueggtw04** [comment]
奇怪, 仍然沒有語言切換的選項, 不知道哪裡出了問題。

OS: Android 11
Phone: Asus Zenfone 6

**Comment by shuping2021** [comment]
切換語言測試：繁中、簡中、English => OK

另外，請問一下，剛突然發現我的APP帳號頁面中沒有 "登出"  icon，是因為測試版沒放上去嗎？
Android版本：9

**Comment by totality-of-life** [comment]
> 切換語言沒問題。
> "Language"按鈕本身沒有切成繁中/簡中(這個應該算使用者介面)
> 沒有報名的課程可能是因為沒有影片的關係，所以專輯名稱有改語言，但內容影片標題維持繁體中文

謝謝，這個是bug沒改到

**Comment by totality-of-life** [comment]
> 切換語言測試：繁中、簡中、English => OK
> 
> 另外，請問一下，剛突然發現我的APP帳號頁面中沒有 "登出" icon，是因為測試版沒放上去嗎？
> Android版本：9

這個因為之前很多人進入帳號頁，忘了有上一頁可以按，結果只發現一個登出可以按，就按登出了，衍生了很多客服要一對一教學。
後來，曾經有讀者問，為什麼要留下登出當陷阱，想想也對，我們就把登出拿掉了。
如果真的要登出，那可以殺掉App重新安裝。

**Comment by totality-of-life** [comment]
> 奇怪, 仍然沒有語言切換的選項, 不知道哪裡出了問題。
> 
> OS: Android 11
> Phone: Asus Zenfone 6

https://play.google.com/store/apps/details?id=app.totality
https://play.google.com/apps/testing/app.totality
試試看去這邊可以更新到最新的測試版嗎？
會不會是你關閉了app自動更新之類的設定

**Comment by totality-of-life** [comment]
> 切換語言沒問題。
> "Language"按鈕本身沒有切成繁中/簡中(這個應該算使用者介面)
> 沒有報名的課程可能是因為沒有影片的關係，所以專輯名稱有改語言，但內容影片標題維持繁體中文

Language可能會一直保持著，因為預設是繁體中文，大部分的人不用改，這功能本來就是為了對中文不熟悉的用戶，其實人數不多。
主要是博士也會用App，可是博士非常忙，而且讀中文相對吃力，所以做了這個功能減輕他負擔，畢竟他都撥出時間聽App陪我們共修了。

**Comment by bueggtw04** [comment]
> > 奇怪, 仍然沒有語言切換的選項, 不知道哪裡出了問題。
> > OS: Android 11
> > Phone: Asus Zenfone 6
> 
> https://play.google.com/store/apps/details?id=app.totality
> https://play.google.com/apps/testing/app.totality
> 試試看去這邊可以更新到最新的測試版嗎？
> 會不會是你關閉了app自動更新之類的設定

不好意思, 確實關掉 App 自動更新的設定了, 
語言更換功能正常, 多謝。

**Comment by shuping2021** [comment]
此次的版本更新，帳號頁面的主要資訊已經能夠跟著語言設定變更顯示，讚喔！

**Comment by Yunarena** [comment]
除了讀書會以外，其他影片標題都有繁簡英=>OK
UI語言切換繁簡英=>OK

**Comment by Happyscorpion** [comment]
更新到2.0版後測試
除了讀書會以外，其他影片標題都有繁簡英=>OK
語言切換繁簡英=>OK

**Comment by Happyscorpion** [comment]
切換成英文版後，「不費力的自我結構調整」這堂課點進去的下一頁，音檔標題名稱是英文沒錯，**但大標題是中文**，也就是「不費力的自我結構調整」這幾個字是中文~

「結構調整」 「螺旋舞」 「落在地球」 「集體的失憶」 「定」這幾堂課也都是如同上面一樣。

「十字路口」 「插對頭」 「我是誰」這三個課程點進去後的內頁，不管是大標題或是音檔標題都是中文，我猜應該是還未拿到正式英文名稱，我還是一併寫上提供您參考哦~ ^^

**Comment by totality-of-life** [comment]
> 切換成英文版後，「不費力的自我結構調整」這堂課點進去的下一頁，音檔標題名稱是英文沒錯，**但大標題是中文**，也就是「不費力的自我結構調整」這幾個字是中文~
> 
> 「結構調整」 「螺旋舞」 「落在地球」 「集體的失憶」 「定」這幾堂課也都是如同上面一樣。
> 
> 「十字路口」 「插對頭」 「我是誰」這三個課程點進去後的內頁，不管是大標題或是音檔標題都是中文，我猜應該是還未拿到正式英文名稱，我還是一併寫上提供您參考哦~ ^^

可以到play store確認一下有更新到最新的版本嗎？建議可以把自動更新打開，會比較方便。
你的分頁tab上面是顯示英文嗎？最新的版本連同分頁tab的文字都會跟著設定語言變動，沒有的話應該還是更早的版本。

**Comment by Happyscorpion** [comment]
> > 切換成英文版後，「不費力的自我結構調整」這堂課點進去的下一頁，音檔標題名稱是英文沒錯，**但大標題是中文**，也就是「不費力的自我結構調整」這幾個字是中文~
> > 「結構調整」 「螺旋舞」 「落在地球」 「集體的失憶」 「定」這幾堂課也都是如同上面一樣。
> > 「十字路口」 「插對頭」 「我是誰」這三個課程點進去後的內頁，不管是大標題或是音檔標題都是中文，我猜應該是還未拿到正式英文名稱，我還是一併寫上提供您參考哦~ ^^
> 
> 可以到play store確認一下有更新到最新的版本嗎？建議可以把自動更新打開，會比較方便。 你的分頁tab上面是顯示英文嗎？最新的版本連同分頁tab的文字都會跟著設定語言變動，沒有的話應該還是更早的版本。


我截圖給你參考看看喔▼
![Screenshot1](https://user-images.githubusercontent.com/90361734/135396527-bb051baf-2ea8-4472-9792-6b6da92ea705.png)

我看我的APP版本是2.0版，是最新的版本了，昨天跟今天(剛剛)都有手動更新過▼
或是 我是不是沒有正確更新到? 
![Screenshot2](https://user-images.githubusercontent.com/90361734/135396688-543d8c25-25b5-473e-8b4f-cbb5c615272a.png) #

**Comment by Yunarena** [comment]
我剛剛從play store更新了最新版，多了很多專輯，確實切到英文再點各專輯之後，影片標題都變成英文，但上面有個專輯標題大字，有些依然是中文：「沒有路的路」「唯識的每日靜心」「不費力的自我結構調整」「結構調整」「螺旋舞」「插對頭」「十字路口」「定」「落在地球」「集體的失憶」「我是誰」

**Comment by totality-of-life** [comment]
感謝！ 這是未購買的課程頁面，那邊沒改到，謝謝幫我抓出來。

其實完整的Version除了版本號2.0還有build number，每次上傳到google，build number要改一次，
ios那邊apple會給測試者看，android這邊沒有顯示，所以總是會造成困擾。我也搞不清楚回報的人切確有沒有裝最新的版本，只能去play store直接看有沒有新版可以抓，沒有就是最新的了。
可能還是把自動更新打開會比較方便。

**Comment by Happyscorpion** [comment]
> 感謝！ 這是未購買的課程頁面，那邊沒改到，謝謝幫我抓出來。
> 
> 其實完整的Version除了版本號2.0還有build number，每次上傳到google，build number要改一次， ios那邊apple會給測試者看，android這邊沒有顯示，所以總是會造成困擾。我也搞不清楚回報的人切確有沒有裝最新的版本，只能去play store直接看有沒有新版可以抓，沒有就是最新的了。 可能還是把自動更新打開會比較方便。

謝謝說明，了解了~ 已經把自動更新打開了^^

**Comment by Hsuan-fei** [comment]
> 切換語言沒問題。 "Language"按鈕本身沒有切成繁中/簡中(這個應該算使用者介面) 沒有報名的課程可能是因為沒有影片的關係，所以專輯名稱有改語言，但內容影片標題維持繁體中文

我看到的狀況是，[沒有報名的課程]專輯名稱均為英文。內容的部分，幾乎都改成英文了，除了讀書會、十字路口、插對頭、我是誰，這四個專輯內容為中文顯示。

**Comment by totality-of-life** [comment]
> > 切換語言沒問題。 "Language"按鈕本身沒有切成繁中/簡中(這個應該算使用者介面) 沒有報名的課程可能是因為沒有影片的關係，所以專輯名稱有改語言，但內容影片標題維持繁體中文
> 
> 我看到的狀況是，[沒有報名的課程]專輯名稱均為英文。內容的部分，幾乎都改成英文了，除了讀書會、十字路口、插對頭、我是誰，這四個專輯內容為中文顯示。

這是正確的情形，那邊博士沒有給英文標題，目前沒有英文名字的曲目會用繁體中文的名稱取代。
博士也會用App，未來如果博士給了英文標題，會再補上去。
