### ISSUE TITLE
Android 12 閃退

### ISSUE THREAD

**Issue by psmandy** [totality-of-life/testing-android#18]
手機型號:  Pixel 5
OS: Android 12 (可能是官方Beta版)
系統版本號碼: SP1A.210812.015

issue描述:
(1)執行APP後.閃退如影片所示.
(2.) 不會跳出'應用程式錯誤/關閉'的訊息視窗 

https://user-images.githubusercontent.com/5046082/136166379-ee9674ac-94e9-4498-b427-14061879d8ba.mp4

](url)

**Comment by totality-of-life** [comment]
這個更新應該是昨天的事情，很高興這麼快就發現了，其實1.9版App在Android 12應該也一樣會閃退。

https://agirls.aotter.net/post/59714
「除了親生子 Pixel，首波能更新 Android 12 的還包含三星、小米、OPPO、realme、OnePlus、vivo 等手機品牌」

Google的審核已經通過了，稍微等一下測試版上架，應該已經沒問題了，或是設定成自動更新，就會安裝好比較方便。
如果晚上抓到2.1版試試看，還是有問題，我們再來找找，謝謝

Andy

記錄一下發生的問題點：
<img width="1850" alt="Screen Shot 2021-10-06 at 12 42 46 PM" src="https://user-images.githubusercontent.com/72474898/136171795-7853ee00-9242-4e68-a290-8244e69e99ca.png">

**Comment by psmandy** [comment]
![Android12_App2 1](https://user-images.githubusercontent.com/5046082/136173865-75de2c1e-c1f6-4563-9511-8267d5fea1a2.jpg)

謝謝! 原來剛剛測試的是APP 2.0 版. 所以還是閃退
2.1版真的修好了! 終於成功進入登入畫面! (感動~~)

**Comment by psmandy** [comment]
為了讓版主看到status更新.所以reopen. 還是由版主來close issue好了

**Comment by totality-of-life** [comment]
我們先留著這個，我想多找一些android 12的朋友來測試，看看其他功能是不是正常
