### ISSUE TITLE
藍芽設備控制App

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-android#19]

**Comment by roger-chuang** [comment]
2.2版測試藍芽設備控制App沒問題，暫停和繼續撥放都OK。 這個功能對我很有幫助，感謝Andy  (系統:Android 11)

**Comment by shiouhying** [comment]
App 2.2版, Android 11, 使用藍芽耳機(小米AirDots)控制播放和暫停功能正常了. 不論是在app中或者在手機畫面關閉或螢幕鎖定時都可以.
但是在開啟其他app時(例如Richart, Chrome..), 音訊會有幾分之一秒很短暫的切斷現象. 不論是用藍芽耳機或直接用手機喇叭播放都有此現象. 但不是每次, 也不特定哪個app, 同一app開啟時有時會有時不會有切斷現象.

**Comment by totality-of-life** [comment]
> App 2.2版, Android 11, 使用藍芽耳機(小米AirDots)控制播放和暫停功能正常了. 不論是在app中或者在手機畫面關閉或螢幕鎖定時都可以. 但是在開啟其他app時(例如Richart, Chrome..), 音訊會有幾分之一秒很短暫的切斷現象. 不論是用藍芽耳機或直接用手機喇叭播放都有此現象. 但不是每次, 也不特定哪個app, 同一app開啟時有時會有時不會有切斷現象.

感謝回報，我目前重現不出來，是不是要開比較耗資源的app？我明天再試試看。
我另外開一個issue追蹤這個問題，我們改到那邊討論，一個討論串討論同一個問題比較不會亂掉

**Comment by bueggtw04** [comment]
藍芽耳機 測試OK

**Comment by Happyscorpion** [comment]
APP 2.2版，測試藍芽耳機(JLab)控制App沒問題
