### ISSUE TITLE
深色模式（應該是Android 10之後開始支援的）

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-android#20]
![IMAGE 2021-10-17 17:10:57](https://user-images.githubusercontent.com/72474898/137620342-d49eda62-5aaa-441e-9b7a-c7fade00dfc5.jpg)

**Comment by roger-chuang** [comment]
測試深色模式沒問題 ，感謝! (系統:Android 11)

**Comment by bueggtw04** [comment]
深色模式顯示OK。有一個很小的問題, 就是淺色和深色背景切換時, 再點回 App 介面, 正在播放中的音頻會暫停掉。

**Comment by totality-of-life** [comment]
> 深色模式顯示OK。有一個很小的問題, 就是淺色和深色背景切換時, 再點回 App 介面, 正在播放中的音頻會暫停掉。

這是正常的，用Android作業系統的本身設定的介面切換的時候，作業系統其實是重新啟動App
