### ISSUE TITLE
鎖定狀態下的控制面板

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-android#21]
![IMAGE 2021-10-17 17:11:37](https://user-images.githubusercontent.com/72474898/137620377-093798c0-e5af-4078-a0b6-2f17ab121685.jpg)

**Comment by totality-of-life** [comment]
這個也有支援多國語言

**Comment by roger-chuang** [comment]
測試鎖定狀態下的控制面板 OK! 謝謝! (系統:Android 11)

**Comment by Hsuan-fei** [comment]
測試鎖定狀態下的控制面板 OK! 謝謝! (系統:Android 10)

**Comment by bueggtw04** [comment]
鎖定狀態下的控制面板, 測試OK

**Comment by shuping2021** [comment]
測試鎖定狀態下的控制面板 ==> 測試 OK

**Comment by Hsuan-fei** [comment]
> 這個也有支援多國語言
請問在哪裡設置多國語言呢？是否也需要測試看看？

**Comment by totality-of-life** [comment]
> > 這個也有支援多國語言
> > 請問在哪裡設置多國語言呢？是否也需要測試看看？

首頁左上角的人頭可以進入帳號頁，帳號頁下面有個地方可以選擇語言

**Comment by Hsuan-fei** [comment]
> > > 這個也有支援多國語言
> > > 請問在哪裡設置多國語言呢？是否也需要測試看看？
> 
> 首頁左上角的人頭可以進入帳號頁，帳號頁下面有個地方可以選擇語言

我剛剛有順利切換英文和簡體中文。

請問如圖：橘色是[回到這一講的開頭]是嗎？若是，按了之後，確實會一直回到這一講的開端。
藍色是[前進到這一講的結束]嗎？若是，那按了沒有任何效果。

但我看到這兩個符號，會以為是[上一首]和[下一首]耶....

然後，當這一講講完，若我沒去理會手機，螢幕變暗之後，我再打開、再按掉，如此兩三次，鎖定狀態下的控制面板就會消失。
現在想來，直到這一講結束，下圖藍色符號( ►I )  似乎都沒有作用   ，且從頭到尾都是淺灰色。

我的也不像Addy的貼圖，有該講的名稱，以及[沒有路的路]字樣。

![148982](https://user-images.githubusercontent.com/92299561/137634504-416331c5-11b4-4c59-a8fc-aa66390698bc.jpg)
，

**Comment by totality-of-life** [comment]
> > > > 這個也有支援多國語言
> > > > 請問在哪裡設置多國語言呢？是否也需要測試看看？
> > 
> > 
> > 首頁左上角的人頭可以進入帳號頁，帳號頁下面有個地方可以選擇語言
> 
> 我剛剛有順利切換英文和簡體中文。
> 
> 請問如圖：橘色是[回到這一講的開頭]是嗎？若是，按了之後，確實會一直回到這一講的開端。 藍色是[前進到這一講的結束]嗎？若是，那按了沒有任何效果。
> 
> 但我看到這兩個符號，會以為是[上一首]和[下一首]耶....
> 
> 然後，當這一講講完，若我沒去理會手機，螢幕變暗之後，我再打開、再按掉，如此兩三次，鎖定狀態下的控制面板就會消失。 現在想來，直到這一講結束，下圖藍色符號( ►I ) 似乎都沒有作用 ，且從頭到尾都是淺灰色。
> 
> 我的也不像Addy的貼圖，有該講的名稱，以及[沒有路的路]字樣。
> 
> ![148982](https://user-images.githubusercontent.com/92299561/137634504-416331c5-11b4-4c59-a8fc-aa66390698bc.jpg) ，

這個面板的樣子看起來不是我做的那一個，是不是你手機本身自己提供的？用別的app播放音樂的時候是不是也會出現這個面板？

不過就目前的資訊看起來，好像是只有一個音檔在播，所以沒辦法跳下一首，然後這個播放控制好像設計成只有一首歌曲的時候，上一首會是回到這首歌的最前頭，下一首按鈕失效呈現淺色狀態。
可以試試「本機」有兩個以上音檔的情況

**Comment by Hsuan-fei** [comment]
>這個面板的樣子看起來不是我做的那一個，是不是你手機本身自己提供的？用別的app播放音樂的時候是不是也會出現這個面板？
---->  沒錯耶，我剛剛才發現，原來我的手機會自己跑出自己提供的面板。我現在用XPlayer播放，結果面板跟[全部生命]一樣。

>不過就目前的資訊看起來，好像是只有一個音檔在播，所以沒辦法跳下一首，然後這個播放控制好像設計成只有一首歌曲的時候，上一首會是回到這首歌的最前頭，下一首按鈕失效呈現淺色狀態。 可以試試「本機」有兩個以上音檔的情況
---->  「本機」的意思我不清楚是哪裡？但發現兩件事：1.倘若我打開全部生命的[清單]，就會顯示音頻的名稱，以及上下首選項。
![149654](https://user-images.githubusercontent.com/92299561/137831478-eb4cca2b-54b5-44a2-9afb-745f11ee20d1.jpg)

2.倘若我只打開全部生命的[循環]，就會顯示跟之前一樣的面板，亦即沒有音頻名稱，但可以選上下首。
![149656](https://user-images.githubusercontent.com/92299561/137831697-d3cf3609-8b09-4784-8e7a-212e581c3208.jpg)

**Comment by Hsuan-fei** [comment]
但我要如何讓[全部生命]的面板出現呢？謝謝

**Comment by totality-of-life** [comment]
抱歉，我今天人都在外面，手邊沒有電腦，明天再回覆妳，謝謝

**Comment by Hsuan-fei** [comment]
> 抱歉，我今天人都在外面，手邊沒有電腦，明天再回覆妳，謝謝

沒關係，先忙吧！不急啊～^

**Comment by totality-of-life** [comment]
本機，我指的是全部生命app，點進去專輯後，這個畫面的第一個tab
![IMAGE 2021-10-20 11:23:42](https://user-images.githubusercontent.com/72474898/138023092-bd423cfc-26dd-47ce-b337-a43a0c37913c.jpg)

我在網路上查發生這件事的只有看到samsung的手機，這好像是手機廠商做的功能，它提供了叫做Home widget的音樂控制，會取代app本身給的，它可能想要統一管理之類的吧？
這要關掉samsung那個widget面板，應該類似底下這樣做
https://www.hardreset.info/devices/samsung/samsung-galaxy-a32-5g/faq/faq/samsung-home-widget/

我剛跟朋友借了一台samsung手機來測，週末應該會拿到，不然最慢下週二會拿到，如果能解決再請妳幫忙測試，先不用操心這件事情，謝謝。

**Comment by Happyscorpion** [comment]
鎖定狀態下的控制面板, 測試OK
