### ISSUE TITLE
深色模式的問題

### ISSUE THREAD

**Issue by Hsuan-fei** [totality-of-life/testing-android#22]
請問深色模式要到哪裡更改呢？因為我更新為測試版後，介面看起來仍跟原來一樣，是白色底。謝謝

**Comment by totality-of-life** [comment]
Android 10以後，到作業系統本身的 設定=>顯示 就可以改了。
![IMAGE 2021-10-17 17:27:01](https://user-images.githubusercontent.com/72474898/137621042-00b42113-feef-481e-8202-c92571723885.jpg)

**Comment by Hsuan-fei** [comment]
設定好了之後，果然全部生命app就變成黑色背景了。
