### ISSUE TITLE
開啟其他app時(例如Richart, Chrome..), 音訊會有幾分之一秒很短暫的切斷現象

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-android#23]
在開啟其他app時(例如Richart, Chrome..), 音訊會有幾分之一秒很短暫的切斷現象. 不論是用藍芽耳機或直接用手機喇叭播放都有此現象. 但不是每次, 也不特定哪個app, 同一app開啟時有時會有時不會有切斷現象.

_Originally posted by @shiouhying in https://github.com/totality-of-life/testing-android/issues/19#issuecomment-945091953_

**Comment by Hsuan-fei** [comment]
我聽全部生命時，也試著開其他app，不知道是幾分之一秒太短暫我沒發現切斷現象，或者我的手機沒這個狀況。我會再留意看看。

**Comment by Hsuan-fei** [comment]
我今天也發生了，開別的app 時會暫時停頓，點進app 的畫面時有時也會。 剛剛點進這個頁面 要記錄，結果全部生命整個停了。我回去要看看狀況，結果運作中的app 整個變空白。必須關掉全部生命再重開。

**Comment by totality-of-life** [comment]
最新的版本應該已經不會發生這個現象，如果還有問題請再回報，謝謝

**Comment by shiouhying** [comment]
已經沒有這個現象了，太讚了！謝謝！
