### ISSUE TITLE
2.2版聽一段時間後自動停止

### ISSUE THREAD

**Issue by roger-chuang** [totality-of-life/testing-android#24]
我是用藍芽耳機，Android 11，聽一段時間後自動結束音頻，我以為耳機沒電，但查看後耳機是有電的，此狀況目前發生有2次，目前繼續聽音頻測試。(我有開其他遊戲APP測試，遊戲會自動跑，之前同時開沒問題)

**Comment by totality-of-life** [comment]
> 我是用藍芽耳機，Android 11，聽一段時間後自動結束音頻，我以為耳機沒電，但查看後耳機是有電的，此狀況目前發生有2次，目前繼續聽音頻測試。(我有開其他遊戲APP測試，**遊戲會自動跑**，之前同時開沒問題)

這邊看不懂意思

**Comment by roger-chuang** [comment]
就是遊戲有自動進行功能(棒球遊戲自動進行N場，無須手動進行比賽)，可以專心聽音頻

**Comment by totality-of-life** [comment]
> 就是遊戲有自動進行功能(棒球遊戲自動進行N場，無須手動進行比賽)，可以專心聽音頻

可以告訴我哪個遊戲，我也去抓來跑跑看。

就你描述的遊戲這個部分比較像是遊戲打開的時候，會跟系統說「我要發出聲音」，這時候全部生命App會把自己正在播放的東西暫停。如果使用youtube，也會有同樣效果。
這種中斷，就算那個app結束了，全部生命app不會自動繼續播放。

另一種是暫時性的中斷，類似簡訊通知、電話響了...這類的，全部生命app也會暫停，可是等到結束，又會自動開始播放

藍芽的部分，我正在實驗。我之前有測試過丟著手機播放整晚，可是我沒有試過用藍芽聽整個晚上。

**Comment by roger-chuang** [comment]
不是打開遊戲時中斷(目前2.2版跟以前都不會中斷)，而是遊戲和全部生命APP都進行一段時間後，全部生命APP會自動結束(完全沒碰設備的情況)，但遊戲還在繼續進行，但後來又繼續測試到目前還沒停止過，也許是我個人的設備問題，如果有其他人也有問題，那可能就有問題了。

**Comment by totality-of-life** [comment]
> 不是打開遊戲時中斷(目前2.2版跟以前都不會中斷)，而是遊戲和全部生命APP都進行一段時間後，全部生命APP會自動結束(完全沒碰設備的情況)，但遊戲還在繼續進行，但後來又繼續測試到目前還沒停止過，也許是我個人的設備問題，如果有其他人也有問題，那可能就有問題了。

我大概知道是什麼問題造成的了。

正常情形，只要開始播音樂，鎖定螢幕會有控制面板跑出來，長駐在手機最上欄位那個地球的圖示也會跑出來，可是有時候會壞掉，這時候，App就無法長時間在背景播放，我目前還不知道為什麼會壞掉，要找找看。
發生這個bug的時候，目前你可以先強制關閉全部生命App，重新打開，就會好

**Comment by roger-chuang** [comment]
> 
> 
> > 不是打開遊戲時中斷(目前2.2版跟以前都不會中斷)，而是遊戲和全部生命APP都進行一段時間後，全部生命APP會自動結束(完全沒碰設備的情況)，但遊戲還在繼續進行，但後來又繼續測試到目前還沒停止過，也許是我個人的設備問題，如果有其他人也有問題，那可能就有問題了。
> 
> 我大概知道是什麼問題造成的了。
> 
> 正常情形，只要開始播音樂，鎖定螢幕會有控制面板跑出來，長駐在手機最上欄位那個地球的圖示也會跑出來，可是有時候會壞掉，這時候，App就無法長時間在背景播放，我目前還不知道為什麼會壞掉，要找找看。 發生這個bug的時候，目前你可以先強制關閉全部生命App，重新打開，就會好

看起來好像跟你說的鎖定螢幕會有控制面板有關，因為剛開始我是先測試這個控制面板問題，然後就接著進行遊戲和全部生命系列APP，也許就是你說的這個問題。

**Comment by Hsuan-fei** [comment]
我不是用藍芽，播放一段時間之後，會自動停止。待我按一下手機[開啟鍵]之後，才繼續播放，但沒播多久，又停掉。再按[開啟鍵]，才再繼續。重複數次，然後每次停頓間隔的時間越來越短，也就是，原本可能10分鐘停一次，後來變8分鐘、6分鐘....。這情況發生在我開了很多app的情況下。

隨後我將其他app關掉，只留[全部生命]，也有相同情況出現，每次停頓間隔的時間也如上述，越來越短。

**Comment by totality-of-life** [comment]
> 我不是用藍芽，播放一段時間之後，會自動停止。待我按一下手機[開啟鍵]之後，才繼續播放，但沒播多久，又停掉。再按[開啟鍵]，才再繼續。重複數次，然後每次停頓間隔的時間越來越短，也就是，原本可能10分鐘停一次，後來變8分鐘、6分鐘....。這情況發生在我開了很多app的情況下。
> 
> 隨後我將其他app關掉，只留[全部生命]，也有相同情況出現，每次停頓間隔的時間也如上述，越來越短。

目前暫時的解決方法是先把全部生命app關掉，重新啟動app，就會好。

--
這個bug的原因是android要求app要在背景跑的時候，要提供一個notification面板，告訴使用者有這麼一個app還在背景執行，讓使用者知道，這樣如果想關掉可以關掉，才不會在偷偷在那邊耗電。

如果記得在之前的版本，我們就是一直顯示一個空的面板，只有文字，沒有任何操作的功能。當時因為共修前時間很趕，所以我採取了一個應急的做法，只是讓Android系統不要關掉我們的app，這樣才能在背景一直聽。

這次更新有足夠的時間把控制面板做完，而不只是一個空的沒有功能的。也做了判斷在app有音樂在播的時候，才會喚醒這個面板，通知系統不要關掉我們。

現在的bug是，我可能哪邊寫錯，所以造成我們app播音樂的時候該喚醒卻沒有喚醒面板，所以就被android作業系統為了省電殺掉了app。

明天再來找到底哪邊寫錯了，抱歉造成大家困擾，大家早點休息

**Comment by Hsuan-fei** [comment]
> > 我不是用藍芽，播放一段時間之後，會自動停止。待我按一下手機[開啟鍵]之後，才繼續播放，但沒播多久，又停掉。再按[開啟鍵]，才再繼續。重複數次，然後每次停頓間隔的時間越來越短，也就是，原本可能10分鐘停一次，後來變8分鐘、6分鐘....。這情況發生在我開了很多app的情況下。
> > 隨後我將其他app關掉，只留[全部生命]，也有相同情況出現，每次停頓間隔的時間也如上述，越來越短。
> 
> 目前暫時的解決方法是先把全部生命app關掉，重新啟動app，就會好。
> 
> -- 這個bug的原因是android要求app要在背景跑的時候，要提供一個notification面板，告訴使用者有這麼一個app還在背景執行，讓使用者知道，這樣如果想關掉可以關掉，才不會在偷偷在那邊耗電。
> 
> 如果記得在之前的版本，我們就是一直顯示一個空的面板，只有文字，沒有任何操作的功能。當時因為共修前時間很趕，所以我採取了一個應急的做法，只是讓Android系統不要關掉我們的app，這樣才能在背景一直聽。
> 
> 這次更新有足夠的時間把控制面板做完，而不只是一個空的沒有功能的。也做了判斷在app有音樂在播的時候，才會喚醒這個面板，通知系統不要關掉我們。
> 
> 現在的bug是，我可能哪邊寫錯，所以造成我們app播音樂的時候該喚醒卻沒有喚醒面板，所以就被android作業系統為了省電殺掉了app。
> 
> 明天再來找到底哪邊寫錯了，抱歉造成大家困擾，大家早點休息

Andy辛苦你了，我雖然看不懂你寫的，但感覺是個很複雜、龐大的工程。感謝你費心! 晚安~

**Comment by roger-chuang** [comment]
今天早上聽的時候也出現一次自動結束，看到其他朋友也有發生，那就真的有問題，看來有點複雜，Andy辛苦您了，感恩!

**Comment by totality-of-life** [comment]
剛上傳了一個應該可行的解法的版本，google審核過了就會自動發佈到play store，理論上應該最慢明天中午就可以抓到，請大家請再試試看。
建議還是把自動更新打開比較方便

**Comment by totality-of-life** [comment]
應該已經修好了，如果還有問題請再回報，謝謝大家

**Comment by roger-chuang** [comment]
> 
> 應該已經修好了，如果還有問題請再回報，謝謝大家

自從更新後到目前好像沒有中斷過了，Andy 辛苦了! 謝謝!
