### ISSUE TITLE
測試2.2版本

### ISSUE THREAD

**Issue by Miffy9145** [totality-of-life/testing-android#25]
剛剛已可以更新2.2版本(是Android 11版本)

黑屏模式→OK

發現使用全部生命的App 不會長駐在手機最上欄位(那個地球的圖示沒有顯示)，所以就沒有在螢幕鎖定的控制看板了。

**Comment by totality-of-life** [comment]
目前的版本應該已經修好了，請再試試看，謝謝

**Comment by totality-of-life** [comment]
#24
