### ISSUE TITLE
APP閃退

### ISSUE THREAD

**Issue by shuping2021** [totality-of-life/testing-android#28]
測試版本：Android 7.0 NRD90M
問題一：
1.選按"同步"
2.選按"播放"
==>閃退

問題二：
random 選按"循環"、"播放"、"同步"、"清單"三次左右，就會發生閃退。

問題三：
清單無法切換On/Off

**Comment by totality-of-life** [comment]
感謝很快發現 and 回報。

這個問題已經修好，新的測試版已經送去給google審核，大概五六個小時到一天就會上架，請大家明天再試試看。

暫時先別按「同步」跟「清單」兩個按鈕，App應該就可以使用。

ps.
這個問題是我耍笨，因為同步的時間點是只有單曲。所以，“同步”on 要把“清單”off，“清單”on 要把“同步”off，可是我忘了檢查現在是on or off，現在變成一直去呼叫對方要切，然後就造成他們不停的在切換到閃退。很瞎，我自己居然沒測試到。

Andy

**Comment by shuping2021** [comment]
閃退的問題已經修復了，謝謝Andy！
