### ISSUE TITLE
"同步"和"清單"選項一開始都是On

### ISSUE THREAD

**Issue by shuping2021** [totality-of-life/testing-android#29]
在更新APP後，第一次進入播放頁面時，會看到"循環"、"同步"、"清單"都顯示"On"的狀態。
在沒有選按這三個中的任一選項時，選按"播放"，此時是同步播放，待音檔同步播放完畢後，會自動進入"清單"模式，也就是播放下一個檔案，自動停止同步，但此時"同步"選項依然是"On"的狀態。

**Comment by totality-of-life** [comment]
感謝妳的細心，這要改一下每個狀態的預設值，已經改好給google審核了，明天就會好。

**Comment by shuping2021** [comment]
初始設定的問題已修復，目前測試都OK了！
謝謝Andy！
