### ISSUE TITLE
全部生命app

### ISSUE THREAD

**Issue by 1314main** [totality-of-life/testing-android#7]
真原醫運動新觀念的雲端內沒有音檔
其它的都ok

**Comment by totality-of-life** [comment]
真原醫運動新觀念的影片，因為夢怡還在忙著整理共修的QA，還沒有把檔案給我，所以裡面是空的，要等個幾天，別擔心，這是正常的

**Comment by roger-chuang** [comment]
已從1.9測試版升級到2.0測試版的，登入沒問題，下載的音檔也都還在，愛心也都還在，目前是正常狀態，繼續觀察一段時間。
