### ISSUE TITLE
真原醫運動新觀念的影片，因為夢怡還在忙著整理共修的QA，還沒有把檔案給我，所以裡面是空的，要等個幾天，別擔心，這是正常的

### ISSUE THREAD

**Issue by totality-of-life** [totality-of-life/testing-android#8]

**Comment by john-huang-x** [comment]
除了這個，愛心與下載內容都正常，也可以聽，Icon變大了

**Comment by totality-of-life** [comment]
icon變大是什麼意思，是app內album的icon還是app的icon?
方便截圖給我看一下嗎？

**Comment by john-huang-x** [comment]
App的icon，不是album的
![Screenshot_20210910-172434237 (1)](https://user-images.githubusercontent.com/90365038/132832544-7e70be75-9629-4819-8dc3-9eb2c0e0672d.jpg)

**Comment by totality-of-life** [comment]
謝謝
這是比較新的Android版本，他要求提供一張圓的Icon圖片，共修前的版本漏掉了，這次補上了

**Comment by john-huang-x** [comment]
影片功能蠻不錯的，會有投放chromecast的功能嗎? 想放到電視看
已下載那條底線和影片黑框合而為一了 :D
![Screenshot_20210910-173256438](https://user-images.githubusercontent.com/90365038/132833923-aa86d240-4bb5-48d8-b696-54678c1a38bc.jpg)

**Comment by totality-of-life** [comment]
chromecast 不知道為什麼我忘記它的存在了，我只支援了iOS的apple TV，昨天iOS那邊也提出希望支援，我今天剛訂了一個chromecast要三天才會送到，所以寫完支援，測試，最快也是下一個版本的事情了。

**Comment by shuping2021** [comment]
我家是可以支援無線投影的智慧電視，剛試了一下投影到電視上觀看，挺不錯的~
